### ISSUE TITLE
Assert in cubeb_resampler_speex::fill_internal_input triggering in test_record on Win32

### ISSUE THREAD

**Issue by kinetiknz** [kinetiknz/cubeb#156]
Noticed this while running tests on the CMake branch.  It seems to take a number of runs of test_record to trigger, e.g. 1 in 20 or so, and then I hit:

`assert(input_buffer && input_frames_count && *input_frames_count && !output_buffer);`

With `*input_frames_count` == 0, which comes from an empty stm->linear_input_buffer in refill_callback_input.

**Comment by padenot** [comment]
I think I've seen that as well, but I'm not too sure since I was modifying exactly some code that could have caused it.

In any case, this is not really hard to fix, we can simply not call into the resampler when in input-only scenario until we have some real data.

Usually, opening the input stream is quick and audio frames flow right away, but of course, sometimes something happens, and we can come up in a situation where we have been signaled that there would be data available, but they're not quite ready.
