### ISSUE TITLE
wasapi breaks threading assumption made by ring_buffer_base

### ISSUE THREAD

**Issue by shuffle2** [kinetiknz/cubeb#320]
cubeb uses multiple threads to implement a fast logger. The logger uses `ring_buffer_base` to pass messages from log producer to log consumer. `ring_buffer_base` [asserts that the thread_id of the producer and consumer are constant](https://github.com/kinetiknz/cubeb/blob/master/src/cubeb_ringbuffer.h#L317).

However, the wasapi implementation (at least - i haven't tested others) will create and destroy producer threads dynamically. As an aside, the consumer is a detached thread which seems kind of gross.

I've made a write-up here: https://github.com/dolphin-emu/dolphin/pull/5256#issuecomment-305950712

**Comment by achronop** [comment]
> I've made a write-up here: dolphin-emu/dolphin#5256 (comment)

A work around to that problem would be to remove that line:
https://github.com/kinetiknz/cubeb/blob/master/src/cubeb.c#L636

We try to detach the thread before the start of audio callback but during the initialization of the logger ring buffer stores the thread id in order to assert that it's single producer single consumer. By removing that line the initialization will take place at first logging of audio callback and the SPSC requirement will be fulfilled.

**Comment by shuffle2** [comment]
@achronop That change doesn't affect this - in my case `log_level` is `CUBEB_LOG_NORMAL` so that log was not being done, anyway.

The issue is that `producer_id` is constant once it is initialized. However the producer thread is recreated each time streaming is started.

**Comment by padenot** [comment]
This has been done in a rush to debug something we weren't able to reproduce reliably (a clock drift).

It's time to fix it proper, I'll get to it soon.

**Comment by padenot** [comment]
This is going to be fixed in two steps:

- First, adding a thread reset API, and calling it in the right locations
- Second (a bit later), having a proper MPSC queue for logging

Also, I agree with the fact that using a detached thread is questionable, but I needed something quickly. We can certainly make it better, it should not be too hard.
