### ISSUE TITLE
api inconsistancy with *_get_min_latency

### ISSUE THREAD

**Issue by mdsitton** [kinetiknz/cubeb#332]
Is there any real reason that `cubeb_get_min_latency`(and the underlying backend api's) take the `cubeb_stream_params` by value instead of maybe const pointer?

`cubeb_stream_init` takes it via pointer so it seems... off that this wouldn't as well. I dug through all of the api back ends and it seems like using a cost pointer shouldn't really break anything as the params aren't passed by pointer anywhere except for audiotrack(which then doesn't get modified or anything)

**Comment by mdsitton** [comment]
Another inconsistency here, `cubeb_get_min_latency` uses `uint32_t` and `cubeb_stream_init` `unsigned int` each for the frame latency.

**Comment by kinetiknz** [comment]
It's historical.  `cubeb_stream_params` used to be past by value everywhere.  When support for input streams was added, the params passed to `cubeb_stream_init` were changed to be a const pointer so that it was possible to indicate the absence of input or output streams by passing a nullptr for that param.  I'd be fine with making it a const pointer everywhere now, for consistency.

The latency type used by `cubeb_get_min_latency` and `cubeb_stream_init` should be the same, it's a bug that they differ.

**Comment by mdsitton** [comment]
Yeah I'd assume its historical. The reason i bring this up is that the api seems to still be in a lot flux and it looks like something that could be fixed while that is still the case.

**Comment by djg** [comment]
I also noticed the pass-by-value instead of pass-by-pointer for cubeb_get_min_latency when doing the rust port.

Should there be a standard for which types to use? Eg. prefer uint32_t over unsigned int?

**Comment by kinetiknz** [comment]
Fixed in https://github.com/kinetiknz/cubeb/pull/333, thanks!
