### ISSUE TITLE
dolphin-emu: Program sometimes abruptly aborts when stopping emulation

### ISSUE THREAD

**Issue by orbea** [kinetiknz/cubeb#456]
OS: `Slackware64-current`
alsa-lib: `1.1.6`
cubeb: 39b8703
dolphin-emu: https://github.com/dolphin-emu/dolphin/commit/be9437450e62b1786795c41c49d33381a83c3c07

When running dolphin-emu with cubeb it will sometimes abruptly abort the whole program when stopping emulation with the following message.
```
dolphin-emu: pcm.c:1310: snd_pcm_pause: Assertion `pcm' failed.
Aborted
```
The `snd_pcm_pause` function seems to be used in `src/cubeb_alsa.c` in two places, https://github.com/kinetiknz/cubeb/blob/39b87032ee3c1a564e3574555acd86f0db89f88c/src/cubeb_alsa.c#L1192 and https://github.com/kinetiknz/cubeb/blob/39b87032ee3c1a564e3574555acd86f0db89f88c/src/cubeb_alsa.c#L1232

My hypothesis is that this is the result of using `snd_pcm_pause` with hardware that does not support it and this might be solved by checking if that hardware can pause before using it. I see examples of this in other programs like mpv or RetroArch. Since dolphin-emu does not directly use `snd_pcm_pause` I do not think this is their bug, however I am not sure how to correctly test my hypothesis with cubeb. Additionally I can not readily reproduce this issue, but it does happen with some regularity.

Examples:
https://github.com/mpv-player/mpv/blob/e2a616bab20fdc123afc44011521d719fd49b8c3/audio/out/ao_alsa.c#L999
https://github.com/libretro/RetroArch/blob/6ae4350883ace90749a83651944f9e7e802f059f/audio/drivers/alsa.c#L269

And for reference here is `snd_pcm_pause` from `alsa-lib-1.1.6` in `src/pcm/pcm.c`.
```
/**
 * \brief Pause/resume PCM
 * \param pcm PCM handle
 * \param enable 0 = resume, 1 = pause
 * \return 0 on success otherwise a negative error code
 *
 * Note that this function works only on the hardware which supports
 * pause feature.  You can check it via \link ::snd_pcm_hw_params_can_pause() \endlink
 * function.
 *
 * The function is thread-safe when built with the proper option.
 */
int snd_pcm_pause(snd_pcm_t *pcm, int enable)
{
        int err;

        assert(pcm);
        if (CHECK_SANITY(! pcm->setup)) {
                SNDMSG("PCM not set up");
                return -EIO;
        }
        err = bad_pcm_state(pcm, P_STATE_RUNNABLE);
        if (err < 0)
                return err;
        snd_pcm_lock(pcm);
        err = pcm->fast_ops->pause(pcm->fast_op_arg, enable);
        snd_pcm_unlock(pcm);
        return err;
}
```

**Comment by kinetiknz** [comment]
Thanks for reporting and investigating this.  We're not actively supporting the ALSA backend having deprecated it for the PulseAudio backend, so it's unlikely we'll find time to debug and fix this ourselves, but would be happy to review and merge fixes.

It does sound like a feature test for `snd_pcm_pause` is needed, with some other code path to stop and resume the stream for hardware that doesn't support it.

Having said that, this doesn't look like an unsupported feature issue.  If that was the case, I'd expect an error result from `pcm->fast_ops->pause(pcm->fast_op_arg, enable);` which libcubeb's ALSA backend would ignore (since we aren't checking the result of `snd_pcm_pause`).

From the log message `dolphin-emu: pcm.c:1310: snd_pcm_pause: Assertion `pcm' failed.` we're seeing `assert(pcm);` at the top of `snd_pcm_pause` firing, which means the `stm->pcm` passed to `snd_pcm_pause` is a null pointer.  That could be a bug in libcubeb's ALSA backend, or in the caller of the library.  Further logging/debugger would be needed to track down what the root cause is.

**Comment by orbea** [comment]
> Further logging/debugger would be needed to track down what the root cause is.

Would you be able to suggest some methods of accomplishing this? I do not have much experience debugging audio problems unfortunately. I do not have pulseaudio installed and would very much like to see the alsa backend to work well in the future, but I do understand I may be a minority. :)

**Comment by riking** [comment]
Wouldn't it make sense to simply replace the `assert(pcm)` with a `if (!pcm) { return 0; }` ?

If the return value isn't checked, it can't be that important.

**Comment by kinetiknz** [comment]
> Would you be able to suggest some methods of accomplishing this? I do not have much experience debugging audio problems unfortunately. I do not have pulseaudio installed and would very much like to see the alsa backend work well in the future, but I do understand I may be a minority. :)

If you can reproduce it locally, record it under https://github.com/mozilla/rr (if it works with ALSA) until the assert fires, then in a replay set a watchpoint on stm->pcm in gdb and execute backwards until you see where it was cleared.

It'll be tricky if you can't reproduce it locally.  I'd probably start by logging the places stm->pcm is set and cleared, as well as the basic libcubeb API operations (init, start, stop, destroy, etc.) and error returns from those functions, then use that to try to work out the sequence of events that's happening.  Also log all the places where stream_* functions are called recursively to handle the stm->other_stream cases (the other_stream stuff was added after we stopped supporting ALSA, so it has seen less testing and might have new bugs).  Since it's a null pointer, either stm->pcm is never initialized before stream_start is called, or stream_destroy was called and then stream_stop was called on a destroyed stream.

> Wouldn't it make sense to simply replace the assert(pcm) with a if (!pcm) { return 0; } ?
> If the return value isn't checked, it can't be that important.

That's ALSA library code so you'd have to ask them, but it seems reasonable to assert that valid parameters have been passed in.  The bug here is that they haven't been.

The lack of rv check is in the libcubeb code.

**Comment by orbea** [comment]
Sorry for the slow reply, but I spent some time getting rr to build well here and then noticed this critical problem.

> rr currently requires an Intel CPU with Nehalem (2010) or later microarchitecture.

Unfortunately it seems I can't use rr since I have an amd fx-6350 cpu here.

**Comment by orbea** [comment]
I'm not sure what changed, but I can no longer reproduce this issue. I'm going to close this until it does happen again.
