### ISSUE TITLE
WASAPI CoInitialize not called

### ISSUE THREAD

**Issue by codecat** [kinetiknz/cubeb#492]
Initialization with WASAPI fails if `CoInitialize` is not called. As a workaround, I can call `CoInitialize(nullptr)` before calling `cubeb_init` to make it work.

**Comment by kinetiknz** [comment]
The requirement to initialize COM is documented [in cubeb.h](https://github.com/kinetiknz/cubeb/blob/master/include/cubeb/cubeb.h#L414).  We used to initialize COM on behalf of the user, but that was changed in 13d9e2874cb13ece4d14efcf34b086770f0bd624 because it was found to be problematic to maintain COM state on behalf of the caller.

**Comment by kinetiknz** [comment]
Thanks for filing this.  I've submitted a simple PR to assert COM is initialized to avoid this happening by accident.
