### ISSUE TITLE
wsapi EnumAudioEndpoints shows disconnected devices

### ISSUE THREAD

**Issue by lunixbochs** [kinetiknz/cubeb#563]
cubeb's wsapi EnumAudioEndpoints currently uses DEVICE_STATEMASK_ALL but the only usable devices are under DEVICE_STATE_ACTIVE

I think the mask should be changed from ALL to ACTIVE

https://github.com/kinetiknz/cubeb/blob/a1200c3437419c4c8487df4a065782c7d1b7245f/src/cubeb_wasapi.cpp#L2821

https://docs.microsoft.com/en-us/windows/win32/api/mmdeviceapi/nf-mmdeviceapi-immdeviceenumerator-enumaudioendpoints

**Comment by kinetiknz** [comment]
Thanks for the report.  DEVICE_STATEMASK_ALL is used intentionally so that we can report unplugged and disabled devices via `cubeb_device_info`'s `state` field.

If you have a use case where the current behaviour is unsuitable, please let us know and we can discuss a solution.  I'll close this issue for now.
