### ISSUE TITLE
Add capture API [RFC]

### ISSUE THREAD

**Issue by ieei** [kinetiknz/cubeb#61]
@padenot has for a long time been proposing adding capture support to cubeb for use in Firefox.

So how should this be done? Should we break API/ABI?
@padenot has an experimental patch and implementation for WASAPI in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1142613
This patch (Part 1) doesn't currently apply cleanly on top of master, but more interestingly it changes `cubeb_stream_init` to take two params in the form of pointers now. This will absolutely break exiting applications out there. I'm curious to know if this is a problem or not. I'm guessing it is not, and that implementing capture/full duplex support is more important.
Anyway, changing `cubeb_stream_init` like this also makes the stream into a both input and output stream. Is that something that we would like, or should a stream be either input only or output only? I don't know.

The driver for adding capture support to cubeb is that @padenot wants full duplex support which makes it easier to both do drift resampling and to feed AEC used by WebRTC in Firefox more reliably.

Would be nice to get your input here @kinetiknz ! :)

**Comment by kinetiknz** [comment]
I don't think there's any strong reason to preserve existing ABI compatibility.  I'm not aware of any major users outside of Gecko (sadly) and there has never been a "1.0" type release for libcubeb anyway.

We should retain the ability for output-only steams somehow (flag passed to cubeb_stream_init?) in addition to full-duplex streams.  I guess it makes sense to also allow input-only streams for symmetry, although we may not need them.

In terms of the WASAPI implementation, I'd like to split the input, output, and shared state up because the cubeb_stream struct is already pretty unwieldy. 

It looks like the data_callback is called with either an input *or* output buffer in same cases.  Does it make sense to have two callbacks or is it easier to correlate with a single callback?

**Comment by padenot** [comment]
It's better to have one callback here, it lowers the input -> output loopback latency, and makes it easier to correlate timing, as you mention.

**Comment by ieei** [comment]
I have a work in progress branch here, if anyone is interested: https://github.com/ieei/cubeb/tree/wip/fullduplex

This is adding capture support for the audiounit backend (Mac OS X)
* Currently only supports using the preferred sample rate. Which is a requirement when using AU HAL according to Apple docs.

**Comment by kinetiknz** [comment]
This is in now.
